language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install pytest
  - pip install jsonschema

# command to run tests
script: py.test

#after_success:
# - coveralls --output=coverage.json
# - coveralls -v
